### ISSUE TITLE
Fraxswap Deployment on Fraxtal Checklist

### ISSUE THREAD

**Issue by pegahcarter** [FraxFinance/dev-fraxswap#2]
- [x] Import and cleanup old code #1 
- [x] Import new router #3 
- [x] Deploy scripts #4
- [x] Deploy
   - [x] Endpoints for each chain (fraxtal, fraxtal testnet)
   - [x] Verification
- [x] Ownership addresses #4
- [x] Documentation
- [x] Peer review
- [x] Transient storage?
    - Opcodes are not supported until ecotone fork in a month so this will not be applied.
